daemon ok
Server listening on port: 12321
listen socket:3
daemon ok
Server listening on port: 12321
listen socket:3
daemon ok
Server listening on port: 12321
listen socket:3
Master 4170 fork child 4171
Master 4170 fork child 4172
Master 4170 fork child 4173
Master 4170 fork child 4174
Master 4170 fork child 4175
daemon ok
Server listening on port: 12321
listen socket:3
Master 4207 fork child 4208
Master 4207 fork child 4209
Master 4207 fork child 4210
Master 4207 fork child 4211
Master 4207 fork child 4212
child 4212 died
child 4211 died
daemon ok
Server listening on port: 12321
listen socket:3
Master 6018 fork child 6019
Master 6018 fork child 6020
Master 6018 fork child 6021
Master 6018 fork child 6022
Master 6018 fork child 6023
No fileNo filedaemon ok
Server listening on port: 12321
listen socket:3
Master 6404 fork child 6405
Master 6404 fork child 6406
Master 6404 fork child 6407
Master 6404 fork child 6408
Master 6404 fork child 6409
daemon ok
Server listening on port: 12321
listen socket:3
Master 6530 fork child 6531
Master 6530 fork child 6532
Master 6530 fork child 6533
Master 6530 fork child 6534
Master 6530 fork child 6535
HTTP/1.1 200 OK
Date: Sat Mar 12 14:39:33 2011

Content-Type: text/html;charset=utf-8
Content-Length: 21
Server: ZHTTPD 0.0.1

daemon ok
Server listening on port: 12321
listen socket:3
Master 6643 fork child 6644
Master 6643 fork child 6645
Master 6643 fork child 6646
Master 6643 fork child 6647
Master 6643 fork child 6648
HTTP/1.1 200 OK
Date: Sat Mar 12 14:41:44 2011
Content-Type: text/html;charset=utf-8
Content-Length: 21
Server: ZHTTPD 0.0.1

HTTP/1.1 200 OK
Date: Sat Mar 12 14:42:38 2011
Content-Type: text/jpg
Content-Length: 63733
Server: ZHTTPD 0.0.1

HTTP/1.1 200 OK
Date: Sat Mar 12 14:43:15 2011
Content-Type: text/html;charset=utf-8
Content-Length: 43
Server: ZHTTPD 0.0.1

HTTP/1.1 200 OK
Date: Sat Mar 12 14:43:15 2011
Content-Type: text/jpg
Content-Length: 63733
Server: ZHTTPD 0.0.1

HTTP/1.1 200 OK
Date: Sat Mar 12 14:43:22 2011
Content-Type: text/jpg
Content-Length: 63733
Server: ZHTTPD 0.0.1

daemon ok
Server listening on port: 12321
listen socket:3
Master 6784 fork child 6785
Master 6784 fork child 6786
Master 6784 fork child 6787
Master 6784 fork child 6788
Master 6784 fork child 6789
No fileNo fileNo fileNo file